# Generated by Django 4.2.1 on 2023-08-06 15:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_datetime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('gest_buyer', models.BooleanField(default=False)),
                ('gest_name', models.TextField(blank=True, null=True)),
                ('gest_address_number', models.IntegerField()),
                ('gest_address_detail', models.TextField(blank=True, null=True)),
                ('gest_address_street', models.TextField(blank=True, null=True)),
                ('gest_address_sub_district', models.TextField(blank=True, null=True)),
                ('gest_address_district', models.TextField(blank=True, null=True)),
                ('gest_address_province', models.TextField(blank=True, null=True)),
                ('gest_address_post_code', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(default=0)),
                ('buyer_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_user', to=settings.AUTH_USER_MODEL)),
                ('seller_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='tran_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_detail', models.TextField(blank=True, null=True)),
                ('product_price', models.FloatField(blank=True, null=True)),
                ('product_type', models.TextField(blank=True, null=True)),
                ('pic1', models.ImageField(blank=True, null=True, upload_to='')),
                ('pic_link1', models.URLField(blank=True, null=True)),
                ('pic2', models.ImageField(blank=True, null=True, upload_to='')),
                ('pic_link2', models.URLField(blank=True, null=True)),
                ('pic3', models.ImageField(blank=True, null=True, upload_to='')),
                ('pic_link3', models.URLField(blank=True, null=True)),
                ('product_quantity', models.IntegerField(default=1)),
                ('tran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tran_detail', to='customer_app.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='AccountDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_number', models.IntegerField()),
                ('address_detail', models.TextField()),
                ('address_street', models.TextField()),
                ('address_sub_district', models.TextField()),
                ('address_district', models.TextField()),
                ('address_province', models.TextField()),
                ('address_post_code', models.IntegerField()),
                ('phone', models.TextField()),
                ('pic1', models.ImageField(blank=True, null=True, upload_to='')),
                ('pic_link1', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
