# Generated by Django 4.2.1 on 2023-08-06 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tran_details',
            new_name='TranDetails',
        ),
    ]
